### ISSUE TITLE
add logging for every review request, replace dry-run mode with "sandbox" mode

### ISSUE THREAD

**Issue by imsky** [imsky/pull-review#17]

**Comment by tir38** [comment]
I was just about to ask for this feature (more logging). Can you explain sandbox mode? Why did this get closed?

**Comment by imsky** [comment]
@tir38 logging was added as part of CLI mode in https://github.com/imsky/pull-review/commit/851dafdc45b59273ab6962c130c5268dae2de7d3

"sandbox" mode i believe was just renaming the flag to --sandbox, which i ultimately decided not to do
