### ISSUE TITLE
Add support for Github reviewers

### ISSUE THREAD

**Issue by imsky** [imsky/pull-review#54]

**Comment by joseSantacruz** [comment]
+1

**Comment by joseSantacruz** [comment]
any update about this??

**Comment by imsky** [comment]
@joseSantacruz will look into this over the next few days

**Comment by joseSantacruz** [comment]
Hi @imsky  great job on the last changes, only a quick question when do you think this is going to be updated on the docker image??

**Comment by imsky** [comment]
@joseSantacruz as soon as i test it on a live pull request. should be 1-2 days.

**Comment by imsky** [comment]
@joseSantacruz now available in 2.4
