### ISSUE TITLE
Exception every time when a comment contains '/review'

### ISSUE THREAD

**Issue by leshik** [imsky/pull-review#57]
Hi,

I can't make it work – every time when a comment contains `/review`, it throws `400 Bad Request` and an exception:
```
2018-02-12T01:09:19.084Z pull-review TypeError: Cannot read property 'html_url' of undefined
    at /app/src/server.js:39:51
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
What's interesting is that `pull-review` respond with `200 Ok` to all other ordinary comments (that do not content `/review`):

![screenshot 2018-02-12 12 07 40](https://user-images.githubusercontent.com/443678/36089576-af2aaecc-0fed-11e8-8b16-43a40f3c2ebb.png)

Did I miss something or this is a bug?

**Comment by imsky** [comment]
are you using a self-hosted server or the public server?

**Comment by imsky** [comment]
interesting. is your PR public? i'll see if i can replicate this, i'd assume it happens on an issue instead of a PR.

**Comment by leshik** [comment]
Unfortunately, it is in our private repo. I can send you the payload somehow if you wish. The `/review` message was added on the conversation tab of the PR.

edit: I've sent the information to the email from your profile.

**Comment by imsky** [comment]
can replicate with your payload, fix coming up @leshik

**Comment by imsky** [comment]
fixed in 2.3.3

**Comment by leshik** [comment]
Yep, now it works. That was fast, thank you!

**Comment by nicogreenarry** [comment]
I'm having the same issue described above.
(Very cool service, by the way! Even with this issue, it's still very useful to be able to assign PRs from slack.) 

My webhook settings:
![pull-review webhook settings](https://user-images.githubusercontent.com/8515899/46493117-56e27800-c7c4-11e8-8bbd-7895e02c9bbf.png)

And only issue comments are being sent.

It's only comments with "/review" in them that are failing:
![failed review request comments](https://user-images.githubusercontent.com/8515899/46493177-7ed1db80-c7c4-11e8-9e3e-32b11e4935bf.png)

**Comment by imsky** [comment]
@nicogreenarry is your pull request public by any chance? if not, could you send me the payload?

**Comment by nicogreenarry** [comment]
Yes - I was on vacation until today, and just emailed you.

**Comment by imsky** [comment]
@nicogreenarry could you confirm the exact error you're seeing with the payload? i'm using the payload you provided and i can't repro the original bug on this issue. the `html_url` property is parsed correctly.

**Comment by nicogreenarry** [comment]
The response I see in Github's webhook UI is:
```
Headers
Connection: keep-alive
Content-Length: 23
Content-Type: text/html; charset=utf-8
Date: Thu, 04 Oct 2018 17:51:39 GMT
Server: Cowboy
Via: 1.1 vegur
X-Powered-By: Express
X-Ratelimit-Limit: 500
X-Ratelimit-Remaining: 498
Body
Failed to parse request
```

I'm not sure how to reproduce this issue - now when I create a `/review` pull request comment, I don't see anything new in github's list of Recent Deliveries.

**Update:** My difficulty reproducing the issue is probably due to [Github's service issues](https://status.github.com/messages) right now, which includes webhook delivery.

**Update 2:** Weeeeeiird...my original testing with `/review` comments was on 10/4/18. One of those tests _just now_ yielded a review assignment from `pull-review`.
![image](https://user-images.githubusercontent.com/8515899/47321691-6d812f80-d60a-11e8-993d-a05c2dbfaabc.png)

**Comment by imsky** [comment]
that's really strange @nicogreenarry but glad to see review assignments are happening

let me know if you encounter this issue again

**Comment by srm09** [comment]
@imsky I am seeing the above issue mentioned by @nicogreenarry 
Here is the payload, https://gist.github.com/srm09/a49412a421159a7b1430fa22eaa321bf 
and the URL to the PR: https://github.com/srm09/pr-test/pull/5

**Comment by imsky** [comment]
@srm09 the payload is missing, could you re-upload?
