### ISSUE TITLE
What to do with webhook?

### ISSUE THREAD

**Issue by tir38** [imsky/pull-review#71]
Maybe I'm missing something, but what do I do with the github issues-comment webhook? To I need to register this with slack? Set as env var for running on Heroku? Include in `.pull-review` file?

**Comment by imsky** [comment]
@tir38 in order to use the webhook, you need to run pull-review in server mode somewhere (e.g. Heroku), and once it's running, get its URL and use that as the webhook in the GitHub repo settings.

let me know if there's anything i can clarify. any details about how you're using pull-review would be very helpful.

**Comment by tir38** [comment]
_in order to use the webhook, you need to run pull-review in server mode somewhere (e.g. Heroku),_ 

done

_and once it's running, get its URL and use that as the webhook in the GitHub repo settings._

who's URL? Heroku? How does this then integrate with Slack? Or is it one-or-the-other? Slack *or* Heroku.

**Comment by imsky** [comment]
@tir38 yes, Heroku. the public Pull Review Heroku app is running on https://pull-review.herokuapp.com/ - you should have a similar URL available in your Heroku dashboard (the "Open app" button should take you to that URL)

> How does this then integrate with Slack?

Pull Review only integrates with Slack if it's running as a [Hubot](https://hubot.github.com/) plugin - standalone Slack is not yet supported.

> Or is it one-or-the-other? Slack or Heroku.

for now, yes, but you can run Pull Review simultaneously in Slack and Heroku to use both chat-based and PR-comment-based workflows

**Comment by imsky** [comment]
@tir38 does the reply above help answer your questions? let me know if i can clarify anything

**Comment by tir38** [comment]
makes sense.
