### ISSUE TITLE
Adding reviewers not in the reviewers map

### ISSUE THREAD

**Issue by tir38** [imsky/pull-review#73]
Our pull-review file looks like this:

```
version: 1
min_reviewers: 2
max_reviewers: 2
assign_min_reviewers_randomly: true
require_notification: false
use_review_requests: true
reviewers:
  ti***:{}
  ze****:{}
  Gr***:{}
  no***:{}
```
(asterisks just for privacy)

However Pull Review is assigning other github contributors not on that list:

> @me***, @Gr***: please review this pull request.
> 
> Powered by pull-review

Do we have to black-list all contributors not on the `reviewers` list?

**Comment by imsky** [comment]
@tir38 if you set require_notification to true, only reviewers listed in the reviewers section will be assigned

https://github.com/imsky/pull-review#require_notification
