### ISSUE TITLE
Add logging when setting reviewers

### ISSUE THREAD

**Issue by tir38** [imsky/pull-review#78]
I updated our script recently and now I'm seeing this in Heroku logs:

`pull-review {"message":"Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the XXX/YYYY repository."`

Can you log who was *trying* to be assigned as a reviewer? I have no clue which user could be causing this.

**Comment by imsky** [comment]
good call. logging right now is deferred until the whole plan completes:

https://github.com/imsky/pull-review/blob/b7ec86367c5dd8da47bbee719a8272fbb0220433/src/index.js#L129-L134

will update.
